version: '3.4'

services:
    api:
        image: infocalendar-api:latest
        build: ./api
        container_name: api
        ports:
            - 5000:5000
        restart: unless-stopped
    syncer:
        image: infocalendar-syncer:latest
        build: ./syncer
        container_name: syncer
        depends_on:
            - redis
        restart: unless-stopped
    redis:
        container_name: redis
        image: redis:latest
        restart: unless-stopped